# 网站的基本信息
site:
  tab: Kaku # 浏览器标签栏上显示的文本
  title: Kaku的个人博客 # 网站的标题
  description: 记录日常学习成果 # 网站的描述，用于SEO等
  language: zh # 网站的语言，例如 "en" 是英文 
  favicon: /page.ico # 网站的图标，用于浏览器标签栏和其他地方显示
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: winter # 主题的浅色模式
    dark: night # 主题的深色模式
    code: github-dark-default # 代码块的主题 https://shiki.style/themes
  date_format: YYYY年 MMMDD日 ddd # 日期格式设置，支持自定义格式
  blog: # 博客相关配置
    pageSize: 8 # 每页显示的文章数量
  menu: # 菜单配置
    - id: home # 菜单项的唯一标识符
      text: 主页 # 菜单项显示的文本
      href: / # 菜单项链接的地址
      svg: "material-symbols:home-outline-rounded"
      target: _self
  #  - id: about
 #     text: 关于
 #     href: /about
 #     svg: "material-symbols:info-outline-rounded"
  #    target: _self
    - id: blog
      text: 博客
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: 全部博客
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: documentation
          text: 网络安全
          href: /blog/category/Documentation
          svg: "material-symbols:health-and-safety-outline-rounded"
          target: _self
        - id: examples
          text: 其他博客
          href: /blog/category/Examples
          svg: "material-symbols:other-admission-outline-rounded"
          target: _self
        # 子菜单项配置
    - id: project
      text: 项目
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: 朋友
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: contact
      text: 联系
      href: "mailto:contact.gjclovesyourself@163.com"
      title: 为他充电
      target: _blank # 在新标签页打开
      svg: "material-symbols:attach-email-outline-rounded"
      
# 用户的个人信息
user:
  name: Kaku # 用户名
  site: "https://www.kakubatman.xyz/" # 用户的网站链接
  avatar: /portrait.ico # 用户头像路径
  sidebar: # 侧边栏配置
    social:
      - href: "https://afdian.com/a/kaku123" # 链接
        ariaLabel: 为他充电 # 图标的可访问性标签
        title: 为他充电 # 图标的悬浮标题
        svg: "ri:cup-line"
      - href: "https://www.kakubatman.xyz"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://www.kakubatman.xyz"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://www.kakubatman.xyz"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
  footer:
    social:
      - href: "https://afdian.com/a/kaku123" # 链接
        ariaLabel: 为他充电 # 图标的可访问性标签
        title: 为他充电 # 图标的悬浮标题
        svg: "ri:cup-line"
      - href: "https://www.kakubatman.xyz/"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://www.kakubatman.xyz/"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://www.kakubatman.xyz/"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
